# Generated by Django 2.1.5 on 2019-03-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesRecord',
            new_name='AccessRecord',
        ),
    ]
